version: 2
updates:
  # python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"

  # github dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
